# Default initial positions for mantis's ros2_control fake system

initial_positions:
  L_Elbow_Pitch_Joint: 0
  L_Hand_L_Joint: 0
  L_Hand_R_Joint: 0
  L_Shoulder_Pitch_Joint: 0
  L_Shoulder_Roll_Joint: 0
  L_Shoulder_Yaw_Joint: 0
  L_Wrist_Pitch_Joint: 0
  L_Wrist_Roll_Joint: 0
  L_Wrist_Yaw_Joint: 0
  R_Elbow_Pitch_Joint: 0
  R_Hand_L_Joint: 0
  R_Hand_R_Joint: 0
  R_Shoulder_Pitch_Joint: 0
  R_Shoulder_Roll_Joint: 0
  R_Shoulder_Yaw_Joint: 0
  R_Wrist_Pitch_Joint: 0
  R_Wrist_Roll_Joint: 0
  R_Wrist_Yaw_Joint: 0