# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_l_controller
    - arm_r_controller
    - gripper_l_controller
    - gripper_r_controller

  arm_l_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - L_Shoulder_Pitch_Joint
      - L_Shoulder_Yaw_Joint
      - L_Shoulder_Roll_Joint
      - L_Elbow_Pitch_Joint
      - L_Wrist_Roll_Joint
      - L_Wrist_Pitch_Joint
      - L_Wrist_Yaw_Joint
  arm_r_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - R_Shoulder_Pitch_Joint
      - R_Shoulder_Yaw_Joint
      - R_Shoulder_Roll_Joint
      - R_Elbow_Pitch_Joint
      - R_Wrist_Roll_Joint
      - R_Wrist_Pitch_Joint
      - R_Wrist_Yaw_Joint
  gripper_l_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - L_Hand_L_Joint
      - L_Hand_R_Joint
  gripper_r_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - R_Hand_L_Joint
      - R_Hand_R_Joint