# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_l_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_r_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_l_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_r_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_l_controller:
  ros__parameters:
    joints:
      - L_Shoulder_Pitch_Joint
      - L_Shoulder_Yaw_Joint
      - L_Shoulder_Roll_Joint
      - L_Elbow_Pitch_Joint
      - L_Wrist_Roll_Joint
      - L_Wrist_Pitch_Joint
      - L_Wrist_Yaw_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_r_controller:
  ros__parameters:
    joints:
      - R_Shoulder_Pitch_Joint
      - R_Shoulder_Yaw_Joint
      - R_Shoulder_Roll_Joint
      - R_Elbow_Pitch_Joint
      - R_Wrist_Roll_Joint
      - R_Wrist_Pitch_Joint
      - R_Wrist_Yaw_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_l_controller:
  ros__parameters:
    joints:
      - L_Hand_L_Joint
      - L_Hand_R_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_r_controller:
  ros__parameters:
    joints:
      - R_Hand_L_Joint
      - R_Hand_R_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity